---
name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run at 1:00 every day
    - cron: 0 1 * * *

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        platform: [ubuntu-latest]
        lint-stage: [pre-commit, pre-push, manual]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: '**/pyproject.toml'

      - name: Run lint
        run: |
          uv run --extra=dev --python=${{ matrix.python-version }} pre-commit run --all-files --hook-stage ${{ matrix.lint-stage }} --verbose

      - name: Run tests
        run: |
          uv run --extra=dev --python=${{ matrix.python-version }} pytest -s -vvv --cov-fail-under 100 --cov=src/ --cov=tests/ tests/

  completion-ci:
    needs: build
    runs-on: ubuntu-latest
    if: always()  # Run even if one matrix job fails
    steps:
      - name: Check matrix job status
        run: |-
          if ! ${{ needs.build.result == 'success' }}; then
            echo "One or more matrix jobs failed"
            exit 1
          fi
